/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author marij
 */
public class login extends javax.swing.JFrame {

    String user="Mariana", password="123";
    
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconUser = new javax.swing.JLabel();
        LbUser = new javax.swing.JLabel();
        LbPassword = new javax.swing.JLabel();
        TfUser = new javax.swing.JTextField();
        TfPassword = new javax.swing.JTextField();
        LbEntrar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        getContentPane().add(IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        LbUser.setText("Nombre:");
        getContentPane().add(LbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        LbPassword.setText(" Contraseña:");
        getContentPane().add(LbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 70, 20));

        TfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUserActionPerformed(evt);
            }
        });
        getContentPane().add(TfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 200, 30));

        TfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(TfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 200, 30));

        LbEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrar.png"))); // NOI18N
        LbEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbEntrarMouseClicked(evt);
            }
        });
        getContentPane().add(LbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bonito-fondo-de-pantalla-para-celular.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 392, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfUserActionPerformed

    private void TfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPasswordActionPerformed

    private void LbEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbEntrarMouseClicked
        Menu ventana= new Menu();
        //LbEntrar.setIcon(entrarAlter);
        
        if(TfUser.getText().equals(user) && TfPassword.getText().equals(password)){
            ventana.setVisible(true);
            ventana.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_LbEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel LbEntrar;
    private javax.swing.JLabel LbPassword;
    private javax.swing.JLabel LbUser;
    private javax.swing.JTextField TfPassword;
    private javax.swing.JTextField TfUser;
    // End of variables declaration//GEN-END:variables
}
